SELECT r.USER_ID, SUM(ri.TOTAL_FINAL_PRICE) AS total_spent
FROM Receipt r
INNER JOIN Receipts_Item ri ON r.ID = ri.REWARDS_RECEIPT_ID
WHERE MONTH(r.PURCHASE_DATE) = 8
GROUP BY r.USER_ID
ORDER BY total_spent DESC
LIMIT 1;
